remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Mathilde Aguiar
description: I'm currently pursuing my PhD in Natural Language Processing in Paris Saclay University. My PhD topic is "Natural Language Inference for clinical trials". This page showcases my past and ongoing work related to NLP.